train:
  _target_: src.datasets.CustomDatasetAudioOnly
  mix_audio_dir: "/Users/andrewut/Documents/dla/hw2/dla_dataset/audio/train/mix"
  s1_audio_dir: "/Users/andrewut/Documents/dla/hw2/dla_dataset/audio/train/s1"
  s2_audio_dir: "/Users/andrewut/Documents/dla/hw2/dla_dataset/audio/train/s2"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.CustomDatasetAudioOnly
  mix_audio_dir: "/Users/andrewut/Documents/dla/hw2/dla_dataset/audio/train/mix"
  s1_audio_dir: "/Users/andrewut/Documents/dla/hw2/dla_dataset/audio/train/s1"
  s2_audio_dir: "/Users/andrewut/Documents/dla/hw2/dla_dataset/audio/train/s2"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
