train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SISDRiMetrics
    name: "SI_SDRI" # it is better to avoid spaces in names
